[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_decorators = False
no_implicit_optional = True
strict_optional = True

[mypy.plugins.discord.ext.commands]
ignore_missing_imports = True

[mypy.plugins.discord]
ignore_missing_imports = True

[mypy-yt_dlp.*] # Добавляем секцию для yt_dlp и его подмодулей
ignore_missing_imports = True
