[pytest]
asyncio_mode = auto
# Устанавливаем область видимости цикла событий для фикстур по умолчанию 'function'
# Это рекомендуемое значение для будущих версий pytest-asyncio
asyncio_default_fixture_loop_scope = function
filterwarnings =
    # Игнорируем ложные срабатывания RuntimeWarning из-за моков async context managers
    ignore:coroutine '.*dummy_connect' was never awaited:RuntimeWarning
    ignore:coroutine '.*DummySession\.post' was never awaited:RuntimeWarning
     # Игнорируем DeprecationWarning из discord.py (внешняя библиотека)
    ignore:'audioop' is deprecated:DeprecationWarning:discord.player
