[pytest]
asyncio_mode = auto
# Устанавливаем область видимости цикла событий для фикстур по умолчанию 'function'
# Это рекомендуемое значение для будущих версий pytest-asyncio
asyncio_default_fixture_loop_scope = function
