# Новый id и непустой text публикуются один раз после подключения бота.
# Технические обновления не требуют изменения этого файла.
id: "2026.10.05-pdroom-redesign-profile"
title: "всем хай! жёсткое обновление"
text: |
  бот:

  - множество невидимых глазу исправлений, стабильность улучшена
  - теперь можно нажимать правой кнопкой на любое сообщение и делать его цитатой. эту цитату потом можно использовать через команду /quote, выбрав нужного юзера

  [сайт](https://pdroom.ru):

  - полностью обновлён дизайн сайта
  - добавлен профиль (аналог /profile в дискорде), для просмотра нужно залогиниться через дискорд
  - есть незаконченный раздел, о нём пока сказать нечего, но мб будет хайп (для этого тоже нужен будет логин на сайте)

  всем спасибо!
